accounts:
  - authToken: "eyJhbGc...."
    nodeIds: ["node1", "node2", "node3", "node4", "node5"]
  #- authToken: "eyJhbGc...."
  #  nodeIds: ["node6", "node7", "node8", "node9", "node10"]
  # ... Other Accounts